### ISSUE TITLE
Turn things around?

### ISSUE THREAD

**Issue by masaeedu** [GaloisInc/parameterized-utils#123]
Hello there. This is more of a question than an issue, really, but would you mind helping me understand why `Data.Parameterized.List` is defined like this:

```haskell
data List :: (k -> Type) -> [k] -> Type where
```

instead of like this?

```haskell
data List' :: [k] -> (k -> Type) -> Type where
```

Similar question for `Assignment`.

AFAICS we can dispense with the `{Functor,Foldable,Traversable}FC` stuff if we define things the latter way around, because the library would be uniformly dealing with "continuation-monad-kinded types" (i.e. types of kind `(K -> *) -> *`, for some kind `K`). As a result, the analogous `{Functor,Foldable,Traversable}F` equipment should suffice for both "first order" and "higher order" parameterized data types.

I should note that at first glance it seems like turning things around in this way destroys composition. Before we were able to form `List (List (f :: k -> Type)) :: [[k]] -> Type`, but with `List'` there doesn't seem to be an obvious analog.

Well there is a way to do it, it's just kind of tedious. We just have to take the "continuation-monad" bit of "continuation-monad-kinded type" to its logical conclusion:

```haskell
type K r x = (x -> r) -> r

kpure :: a -> K r a
kpure a cb = cb a

type KPure :: x -> K Type x
data KPure a cb = KPure (cb a)

(<=<) :: (b -> K r c) -> (a -> K r b) -> a -> K r c
(bmc <=< amb) a cb = amb a $ kpure cb . bmc

type (<=<) :: (b -> K Type c) -> (a -> K Type b) -> a -> K Type c
newtype (bmc <=< amb) a cb = KCompose { runKCompose :: amb a (KPure cb `Compose` bmc) }
```

Now we can compose `List` with itself like so:

```haskell
test :: (List <=< List) [[Int, String], [Bool]] Identity
test = KCompose $
     Compose (KPure $ Identity 1 :< Identity "foo" :< Nil)
  :< Compose (KPure $ Identity False :< Nil)
  :< Nil
```

_Tedious_! I haven't figured out a way to make this suck less, but I thought I'd dump all this here and see what you folks think of it. Possibly playing around with `join`/`=<<` instead of `<=<` will yield a more ergonomic interface.

---

EDIT: I hadn't paid much attention to the `TestEqualityFC` and `OrdFC` classes in the library, which actually make use of final parameter, and so cannot be substituted with a `*F` version straightforwardly. But these two appear to be the exception rather than the rule.

**Comment by robdockins** [comment]
I think the main reason is more or less the one you are exploring with the "composition" question.  It's important for us to be able to form partial applications of, e.g., `Assignment f`, which becomes impossible (or at least much more difficult) if the arguments are ordered the other way.
