### ISSUE TITLE
Safe Haskell-related build error

### ISSUE THREAD

**Issue by travitch** [GaloisInc/parameterized-utils#139]
When building with a fresh checkout and apparently an old version of th-abstraction, I get the following error:

```
Building library for parameterized-utils-2.1.5.0.99..
[20 of 38] Compiling Data.Parameterized.ClassesC

src/Data/Parameterized/ClassesC.hs:32:1: error:
    Data.Parameterized.Some: Can't be safely imported!
    The module itself isn't safe.
   |
32 | import Data.Parameterized.Some (Some(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I narrowed it down to a reproducible case with the following `cabal.project.freeze`:

```
active-repositories: hackage.haskell.org:merge
constraints: parameterized-utils +unsafe-operations,
             any.th-abstraction ==0.3.2.0

index-state: hackage.haskell.org 2022-07-13T02:14:33Z
```

**Comment by RyanGlScott** [comment]
I'm honestly surprised that `parameterized-utils` ever compiled with `th-abstraction<0.4`, as the use of `Safe` in `Data.Parameterized.ClassesC` doesn't seem to be that new. In any case, perhaps the most expedient thing to do is to raise `parameterized-utils`' lower version bounds on `th-abstraction` to `>= 0.4.2`, as that version marks its modules as `Safe`. That major version of `th-abstraction` has been out long enough where that shouldn't cause any issues with downstream dependencies. I've submitted #140 for this.
