### ISSUE TITLE
support/allow th-abstraction 0.7

### ISSUE THREAD

**Issue by juhp** [GaloisInc/parameterized-utils#161]
It would be nice if parameterized-utils could build with th-abstraction-0.7
(this would prevent having to hold back th-abstraction for copilot in Stackage Nightly).

**Comment by RyanGlScott** [comment]
I've made [a Hackage revision](https://hackage.haskell.org/package/parameterized-utils-2.1.8.0/revisions/) for `parameterized-utils-2.1.8.0` to allow it to build with `th-abstraction-0.7.*`. Please let me know if I should do anything else.

**Comment by juhp** [comment]
Thanks, Ryan!

**Comment by juhp** [comment]
(copilot-3.20 is now in Stackage Nightly btw :-))
