### ISSUE TITLE
Not compatible with lens-5.3

### ISSUE THREAD

**Issue by ysangkok** [GaloisInc/parameterized-utils#163]
It would be nice to revise the latest Hackage package to permit this version of lens. I see that @RyanGlScott has the maintainer flag to be able to do that.

**Comment by RyanGlScott** [comment]
I've [applied a Hackage revision](https://hackage.haskell.org/package/parameterized-utils-2.1.8.0/revisions/) to `parameterized-utils-2.1.8.0`.

**Comment by ysangkok** [comment]
Thank you, much appreciated!
