### ISSUE TITLE
NatRepr should wrap Natural, not Integer

### ISSUE THREAD

**Issue by lukemaurer** [GaloisInc/parameterized-utils#19]
`NatRepr` causes a fair amount of pain by insisting on working with `Integer`s, with all the ensuing runtime checks and `Maybe` churning.  It seems to be relying on `GHC.TypeLits`, which has been superseded by `GHC.TypeNats`, which has the crucial machinery (`natVal` and `someNatVal`) working with `Natural` instead of `Integer`.

Of course, as the user I'd care more about just having `Natural` versions of `someNat` and `natValue`, but avoiding runtime checks by changing the internal representation would also be good.

**Comment by robdockins** [comment]
Agreed, in principle.

I don't know when exactly all the necessary operations in `GHC.TypeNats` became available, so we should find out.  For now we're maintaining compatibility with GHC 8.2, which might be an issue.

**Comment by joehendrix** [comment]
It looks like 4.10.0.0, which was in 8.2.1, so I think this should be safe to migrate.

**Comment by robdockins** [comment]
Done in 0ed820373a7cd60774d9708db6caf4eabc6f88c6
