### ISSUE TITLE
Document that Diff's are added only via the category instance

### ISSUE THREAD

**Issue by glguy** [GaloisInc/parameterized-utils#52]
Functionality as important as adding two `Diff`s together should be documented somewhere explicitly either on the definition of `Diff`, `noDiff`, or should be given its own name like `addDiff` that happens to be the implementation of `(.)`

**Comment by robdockins** [comment]
I'd probably be in favor of a new `addDiff` function with the appropriate documentation, which includes indicating that the `Category` instance uses it.
